#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Documents ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo $tmux_running
echo $selected_name

if [[ -z $tmux_running ]]; then
    echo "new sesh"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

echo "no sesh"

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "has sesh"
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
