#!/bin/sh

echo "$1" > ~/test.txt
if [ -z "$1" ]; then
  url="$(xclip -o)"
else
  url="$1"
fi

echo $url

case "$url" in
  *)
    readable -o /tmp/x.html -s ~/.newsboat/style.css "$url" > /dev/null 2>&1 && setsid -f qutebrowser /tmp/x.html > /dev/null 2>&1
esac
# vim: filetype=sh
