# Use powerline
USE_POWERLINE="true"
EDITOR=nvim
source ~/.config/nvim/plugged/fzf/shell/completion.zsh
source ~/.config/nvim/plugged/fzf/shell/key-bindings.zsh
# Source manjaro-zsh-configuration
if [[ -e ~/dotfiles/zsh/manjaro-zsh-config ]]; then
  source ~/dotfiles/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e ~/dotfiles/zsh/manjaro-zsh-prompt ]]; then
  source ~/dotfiles/zsh/manjaro-zsh-prompt
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


alias vim="nvim"
alias vi="nvim"

neofetch
