# Use powerline
USE_POWERLINE="true"
EDITOR=nvim
source ~/.config/nvim/plugged/fzf/shell/completion.zsh
source ~/.config/nvim/plugged/fzf/shell/key-bindings.zsh

# Source manjaro-zsh-configuration
if [[ -e ~/dotfiles/zsh/manjaro-zsh-config ]]; then
  source ~/dotfiles/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e ~/dotfiles/zsh/manjaro-zsh-prompt ]]; then
  source ~/dotfiles/zsh/manjaro-zsh-prompt
fi

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec


alias vim="nvim"
alias vi="nvim"

ANDROID_SDK=/home/peter/Android/Sdk
BROWSER=/usr/bin/brave
ANDROID_SDK=/home/peter/Android/Sdk

neofetch

alias zathura='zathura --fork'
